import { ArrowRight, CalendarCheck2, Check, ReceiptText, ShieldCheck } from "lucide-react";
import Link from "next/link";

export function HomePage() {
  return <main className="min-h-screen bg-[#f4f1ea] text-[#1f211f]">
    <header className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link href="/" className="text-lg font-bold">SlotPay <span className="text-[#dd594b]">PH</span></Link><nav className="hidden gap-7 text-sm text-zinc-600 sm:flex"><Link href="#how">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/security">Security</Link></nav><div className="flex items-center gap-3"><Link href="/sign-in" className="hidden text-sm font-semibold sm:block">Sign in</Link><Link href="/sign-up" className="rounded-full bg-[#20231f] px-5 py-2.5 text-sm font-semibold text-white">Start free</Link></div></header>
    <section className="mx-auto grid max-w-6xl gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-24"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c94c40]">Built for Philippine appointment businesses</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-7xl">Bookings confirmed.<br/><span className="text-[#dd594b]">Screenshots contained.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-600">Turn scattered chat bookings and reservation-deposit receipts into one calm workflow for your team and customers.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/sign-up" className="inline-flex items-center gap-2 rounded-full bg-[#dd594b] px-6 py-3.5 font-semibold text-white">Start your 14-day trial <ArrowRight className="size-4" /></Link><Link href="/pricing" className="rounded-full border border-black/15 px-6 py-3.5 font-semibold">See pricing</Link></div><p className="mt-4 text-sm text-zinc-500">No card required. Merchant review protects public payment details.</p></div>
      <div className="rounded-[2rem] bg-[#20231f] p-5 text-white shadow-[0_35px_90px_rgba(41,36,31,.22)] sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-sm text-white/50">Today · Glow Studio</p><p className="mt-1 text-2xl font-semibold">12 appointments</p></div><CalendarCheck2 className="size-9 text-[#ff877a]" /></div><div className="mt-5 space-y-3">{[["10:00", "Maria Santos", "Reviewed"],["11:30", "Angela Cruz", "Confirmed"],["14:00", "Bea Reyes", "Awaiting"]].map(([time,name,status], i)=><div key={time} className="grid grid-cols-[55px_1fr_auto] items-center gap-3 rounded-xl bg-white/[.06] p-4"><span className="text-sm text-white/50">{time}</span><span className="font-medium">{name}</span><span className={`rounded-full px-2.5 py-1 text-xs ${i===2 ? "bg-amber-300/15 text-amber-200" : "bg-emerald-300/15 text-emerald-200"}`}>{status}</span></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#ff877a] p-4 text-[#2b1a17]"><ReceiptText className="size-5"/><p className="mt-5 text-2xl font-bold">₱4,500</p><p className="text-xs">Deposits tracked</p></div><div className="rounded-xl border border-white/10 p-4"><ShieldCheck className="size-5 text-emerald-300"/><p className="mt-5 font-semibold">Human approval</p><p className="mt-1 text-xs text-white/50">OCR never proves payment</p></div></div></div>
    </section>
    <section id="how" className="bg-[#20231f] py-24 text-white"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#ff877a]">One focused workflow</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Less chasing. A clearer appointment book.</h2><div className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 md:grid-cols-3">{[["01","Share one booking link"],["02","Collect the deposit"],["03","Review and confirm"]].map(([n,title])=><article key={n} className="bg-[#20231f] p-7"><span className="text-sm text-[#ff877a]">{n}</span><h3 className="mt-16 text-xl font-semibold">{title}</h3></article>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 py-24 text-center"><h2 className="text-4xl font-semibold tracking-[-.045em]">Start with the booking problem you already have.</h2><div className="mx-auto mt-7 flex max-w-md flex-col gap-3 text-left text-zinc-600">{["14-day free trial", "One business and location", "Manual approval remains in your control"].map(x=><p key={x} className="flex items-center gap-3"><Check className="size-5 text-[#dd594b]"/>{x}</p>)}</div><Link href="/sign-up" className="mt-9 inline-flex rounded-full bg-[#20231f] px-7 py-3.5 font-semibold text-white">Create your workspace</Link></section>
    <footer className="border-t border-black/10"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 px-5 py-8 text-sm text-zinc-500 sm:flex-row"><p>© 2026 SlotPay PH</p><div className="flex flex-wrap gap-5"><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/security">Security</Link><Link href="/acceptable-use">Acceptable use</Link></div></div></footer>
  </main>;
}
